export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";

export const POST_CARD_SUCCESS = "POST_CARD_SUCCESS";
export const POST_CARD_ERROR = "POST_CARD_ERROR";
export const GET_CARD_SUCCESS = "GET_CARD_SUCCESS";
export const GET_CARD_ERROR = "GET_CARD_ERROR";

export const GET_ADDRESSES_SUCCESS = "GET_ADDRESSES_SUCCESS";
